Repository dlang/tools, pull requests merged in 2019-11, with the labels that each got.

#383 Build everything with -preview=dip1000
  posix.mak
Labels: auto-merge

#385 Have tolf keep and/or add terminating newline
  tolf.d
Labels: auto-merge

#386 Fix issue 20386 - extract @betterC unit tests into regular functions
  test/tests_extractor/betterc.d.ext
  tests_extractor.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#387 Merge stable
  test/tests_extractor/betterc.d.ext
  tests_extractor.d
Labels: Bug Fix, auto-merge, stable -> master
