Repository dlang/tools, pull requests merged in 2020-06, with the labels that each got.

#405 Improve regex for closed issues
  changed.d
Labels: Type.Enhancement, auto-merge

#408 Fix issue 13345 - Add argument support to rdmd --eval
  rdmd.d
  rdmd_test.d
Labels: Enhancement, auto-merge

#414 Use system make for tests
  travis.sh
Labels: Prio.5.Trivial

#416 Remove FUNDING.yml
  .github/FUNDING.yml
Labels: Prio.5.Trivial, auto-merge

#404 Update libdparse dependency of test_extractor.d (again)
  tests_extractor.d
Labels: auto-merge

#403 Remove unused code from test_extractor.d
  tests_extractor.d
Labels: auto-merge
